# Generated by Django 3.0.7 on 2020-06-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20200616_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected_handler',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
