# Generated by Django 3.0.7 on 2020-06-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_user_connected_handler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connected_handler',
        ),
    ]
