# Generated by Django 3.0.7 on 2020-06-22 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='unique_code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
