# Generated by Django 3.0.7 on 2020-06-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20200623_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelets', to='userpage.Profile'),
        ),
    ]
