# Generated by Django 3.0.7 on 2020-06-22 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20200622_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 6, 22, 8, 20, 56, 186675, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
    ]
