# Generated by Django 3.0.7 on 2020-06-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20200622_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userpage.Profile'),
        ),
    ]
